# Generated by Django 5.0.6 on 2024-06-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fno', models.IntegerField()),
                ('fname', models.CharField(max_length=25)),
                ('fprice', models.FloatField()),
                ('fseller', models.CharField(max_length=25)),
                ('fcate', models.CharField(max_length=20)),
            ],
        ),
    ]
